/**
 * Canonical patient-facing intake question bank (edge/shared copy).
 */
import type { IntakeQuestion } from "./intake-to-assessment.ts";

/** All production CDS pathway slugs (existing ten plus expansion six). IV uses iv-hydration-only. */
export const CDS_PATHWAY_SLUGS = [
  "weight-loss-glp1",
  "metabolic-recomposition",
  "low-testosterone-trt",
  "hormone-women-bhrt",
  "energy-fatigue-wellness",
  "recovery-injury",
  "libido-sexual-wellness",
  "longevity-wellness",
  "general-wellness",
  "iv-hydration-only",
  "prediabetes-insulin-resistance",
  "male-sexual-function",
  "female-sexual-function",
  "thyroid-optimization",
  "anemia-iron",
  "aesthetics",
] as const;

export type CdsPathwaySlug = (typeof CDS_PATHWAY_SLUGS)[number];

export const INTAKE_QUESTION_BANK: IntakeQuestion[] = [
  {
    id: "safety_pregnant_or_nursing",
    text: "Are you currently pregnant, trying to become pregnant, or breastfeeding?",
    type: "yes_no",
    patientFacing: true,
    tags: {
      contraindicationTags: ["pregnancy", "pregnancy_breastfeeding"],
      hardStop: true,
    },
    routesToPathways: [...CDS_PATHWAY_SLUGS],
  },
  {
    id: "safety_nitrates",
    text: "Do you take nitrates (nitroglycerin, isosorbide) for chest pain or heart conditions?",
    type: "yes_no",
    patientFacing: true,
    tags: { contraindicationTags: ["nitrates"], hardStop: true },
    routesToPathways: [
      "male-sexual-function",
      "libido-sexual-wellness",
      "low-testosterone-trt",
      "general-wellness",
    ],
  },
  {
    id: "safety_recent_cardiac_event",
    text: "Have you had a heart attack, stroke, or cardiac procedure in the last six months?",
    type: "yes_no",
    patientFacing: true,
    tags: { contraindicationTags: ["recent_cardiac_event", "cardiovascular_disease"], hardStop: true },
    routesToPathways: [
      "male-sexual-function",
      "libido-sexual-wellness",
      "low-testosterone-trt",
      "weight-loss-glp1",
      "metabolic-recomposition",
    ],
  },
  {
    id: "safety_uncontrolled_bp",
    text: "Do you have uncontrolled high blood pressure (above 160/100 without treatment)?",
    type: "yes_no",
    patientFacing: true,
    tags: { contraindicationTags: ["uncontrolled_hypertension"], hardStop: true },
    routesToPathways: [
      "male-sexual-function",
      "female-sexual-function",
      "libido-sexual-wellness",
      "iv-hydration-only",
    ],
  },
  {
    id: "safety_active_cancer",
    text: "Do you have active or untreated cancer?",
    type: "yes_no",
    patientFacing: true,
    tags: {
      contraindicationTags: ["active_malignancy", "estrogen_sensitive_cancer", "hormone_sensitive_cancer"],
      hardStop: true,
    },
    routesToPathways: [
      "recovery-injury",
      "hormone-women-bhrt",
      "female-sexual-function",
      "low-testosterone-trt",
      "longevity-wellness",
    ],
  },
  {
    id: "safety_cardiac_conditions",
    text: "Do you have a history of heart failure, arrhythmia, or significant heart disease?",
    type: "yes_no",
    patientFacing: true,
    tags: { contraindicationTags: ["cardiovascular_disease", "chf"], hardStop: true },
    routesToPathways: [...CDS_PATHWAY_SLUGS],
  },
  {
    id: "safety_liver_kidney",
    text: "Do you have significant liver or kidney disease?",
    type: "yes_no",
    patientFacing: true,
    tags: { contraindicationTags: ["egfr_below_30", "esrd"], labTriggers: ["egfr"], hardStop: true },
    routesToPathways: [...CDS_PATHWAY_SLUGS],
  },
  {
    id: "safety_anaphylaxis",
    text: "Have you ever had a severe allergic reaction (anaphylaxis) to medication or IV treatment?",
    type: "yes_no",
    patientFacing: true,
    tags: { contraindicationTags: ["anaphylaxis_history"], hardStop: true },
    routesToPathways: ["iv-hydration-only", "aesthetics", "general-wellness"],
  },
  {
    id: "safety_substance_use",
    text: "Do you have a history of substance use disorder requiring active treatment?",
    type: "yes_no",
    patientFacing: true,
    tags: { hardStop: true },
    routesToPathways: [...CDS_PATHWAY_SLUGS],
  },
  {
    id: "symptoms_experienced",
    text: "What symptoms are you experiencing?",
    type: "multi",
    options: [
      { value: "fatigue", label: "Low energy / persistent fatigue" },
      { value: "brain_fog", label: "Difficulty focusing / brain fog" },
      { value: "weight_gain", label: "Unexplained weight gain" },
      { value: "low_libido", label: "Decreased libido" },
      { value: "poor_recovery", label: "Poor recovery" },
      { value: "joint_pain", label: "Joint / tendon pain" },
      { value: "cold_intolerance", label: "Cold intolerance" },
      { value: "hair_loss", label: "Hair loss" },
      { value: "erectile_dysfunction", label: "Erectile dysfunction" },
      { value: "vaginal_dryness", label: "Vaginal dryness" },
    ],
    patientFacing: true,
    tags: {},
    routesToPathways: [
      "energy-fatigue-wellness",
      "weight-loss-glp1",
      "prediabetes-insulin-resistance",
      "low-testosterone-trt",
      "hormone-women-bhrt",
      "male-sexual-function",
      "female-sexual-function",
      "thyroid-optimization",
      "anemia-iron",
      "recovery-injury",
      "libido-sexual-wellness",
      "longevity-wellness",
      "general-wellness",
    ],
  },
  {
    id: "intake_interest_glp1",
    text: "Are you interested in medical weight loss (GLP-1)?",
    type: "yes_no",
    patientFacing: true,
    tags: { symptomKeys: ["weight_gain"], labTriggers: ["hba1c"] },
    routesToPathways: ["weight-loss-glp1", "prediabetes-insulin-resistance", "metabolic-recomposition"],
  },
  {
    id: "intake_interest_hormones",
    text: "Are you interested in hormone optimization (TRT or BHRT)?",
    type: "yes_no",
    patientFacing: true,
    tags: { labTriggers: ["tsh", "prolactin"] },
    routesToPathways: ["low-testosterone-trt", "hormone-women-bhrt", "thyroid-optimization"],
  },
  {
    id: "intake_interest_sexual_wellness",
    text: "Are you interested in sexual wellness support?",
    type: "yes_no",
    patientFacing: true,
    tags: { symptomKeys: ["low_libido"], labTriggers: ["prolactin"] },
    routesToPathways: ["libido-sexual-wellness", "male-sexual-function", "female-sexual-function"],
  },
  {
    id: "intake_interest_iv",
    text: "Are you interested in IV hydration or NAD+ infusion?",
    type: "yes_no",
    patientFacing: true,
    tags: { symptomKeys: ["dehydration", "nad_interest"] },
    routesToPathways: ["iv-hydration-only"],
  },
  {
    id: "intake_interest_aesthetics",
    text: "Are you interested in cosmetic neuromodulator or filler treatments?",
    type: "yes_no",
    patientFacing: true,
    tags: { symptomKeys: ["facial_wrinkles", "volume_loss"] },
    routesToPathways: ["aesthetics"],
  },
  {
    id: "iv_chf",
    text: "Do you have congestive heart failure (CHF)?",
    type: "yes_no",
    patientFacing: true,
    tags: { contraindicationTags: ["chf"], hardStop: true },
    routesToPathways: ["iv-hydration-only"],
  },
  {
    id: "iv_esrd",
    text: "Do you have end-stage renal disease on dialysis?",
    type: "yes_no",
    patientFacing: true,
    tags: { contraindicationTags: ["esrd"], hardStop: true },
    routesToPathways: ["iv-hydration-only"],
  },
  {
    id: "iv_g6pd",
    text: "Do you have G6PD deficiency?",
    type: "yes_no",
    patientFacing: true,
    tags: { contraindicationTags: ["g6pd_high_dose_vitc"], hardStop: true },
    routesToPathways: ["iv-hydration-only"],
  },
  {
    id: "prediabetes_known_diagnosis",
    text: "Has a provider told you that you have prediabetes or insulin resistance?",
    type: "yes_no",
    patientFacing: true,
    tags: { symptomKeys: ["insulin_resistance"], labTriggers: ["hba1c"] },
    routesToPathways: ["prediabetes-insulin-resistance"],
  },
  {
    id: "male_ed_onset",
    text: "Do you have difficulty getting or maintaining an erection?",
    type: "yes_no",
    patientFacing: true,
    tags: { symptomKeys: ["erectile_dysfunction", "low_libido"] },
    routesToPathways: ["male-sexual-function"],
  },
  {
    id: "female_libido_low",
    text: "Has your interest in sexual activity decreased?",
    type: "yes_no",
    patientFacing: true,
    tags: { symptomKeys: ["low_libido", "reduced_arousal"] },
    routesToPathways: ["female-sexual-function", "libido-sexual-wellness"],
  },
  {
    id: "thyroid_symptoms",
    text: "Do you have symptoms that could relate to thyroid imbalance?",
    type: "yes_no",
    patientFacing: true,
    tags: { symptomKeys: ["fatigue", "weight_gain", "cold_intolerance"], labTriggers: ["tsh"] },
    routesToPathways: ["thyroid-optimization", "energy-fatigue-wellness"],
  },
  {
    id: "anemia_symptoms",
    text: "Do you feel unusually tired, short of breath, or look pale?",
    type: "yes_no",
    patientFacing: true,
    tags: {
      symptomKeys: ["fatigue", "shortness_of_breath", "pallor"],
      labTriggers: ["ferritin", "hemoglobin"],
    },
    routesToPathways: ["anemia-iron", "energy-fatigue-wellness"],
  },
  {
    id: "recovery_injury",
    text: "Are you seeking support for injury recovery or tissue healing?",
    type: "yes_no",
    patientFacing: true,
    tags: { symptomKeys: ["joint_pain", "poor_recovery"] },
    routesToPathways: ["recovery-injury"],
  },
];

export const SEEDED_SYMPTOM_KEYS = [
  "weight_gain",
  "fatigue",
  "brain_fog",
  "low_libido",
  "poor_recovery",
  "joint_pain",
  "increased_thirst",
  "blurred_vision",
  "insulin_resistance",
  "erectile_dysfunction",
  "reduced_morning_erections",
  "vaginal_dryness",
  "reduced_arousal",
  "cold_intolerance",
  "hair_loss",
  "constipation",
  "shortness_of_breath",
  "pallor",
  "heavy_menses",
  "facial_wrinkles",
  "volume_loss",
  "skin_laxity",
  "dehydration",
  "hangover_recovery",
  "nad_interest",
] as const;

export const SEEDED_CONTRAINDICATION_TAGS = [
  "pregnancy",
  "mtc_men2",
  "pancreatitis_history",
  "nitrates",
  "recent_cardiac_event",
  "severe_hypotension",
  "uncontrolled_hypertension",
  "cardiovascular_disease",
  "estrogen_sensitive_cancer",
  "hormone_sensitive_cancer",
  "untreated_adrenal_insufficiency",
  "thyrotoxicosis",
  "cardiac_caution",
  "elderly_caution",
  "hemochromatosis",
  "active_gi_bleed",
  "active_infection",
  "product_allergy",
  "pregnancy_breastfeeding",
  "neuromuscular_disorder",
  "chf",
  "esrd",
  "anaphylaxis_history",
  "g6pd_high_dose_vitc",
  "egfr_below_30",
  "acute_illness",
  "contrast_48h",
  "active_malignancy",
  "active_prostate_cancer",
  "fertility_desire",
  "untreated_severe_osa",
  "uncontrolled_heart_failure",
  "thromboembolic_disease",
  "unexplained_vaginal_bleeding",
  "progesterone_allergy",
  "uncontrolled_diabetes",
] as const;
